insightfinder:
  # The primary configuration for InsightFinder
  url: https://app.insightfinder.com
  username: 
  licenseKey: 
  if_http_proxy:
  if_https_proxy:

powerCollectorAgent:

  # The image of the agent
  image: docker.io/insightfinderinc/power-collector-agent:0.0.1

  # The image pull Secrets
  imagePullSecrets: []

  # The interval for the agent cron
  runInterval: 5 #(minutes)

  # The sampling interval for each project created on InsightFinder website
  samplingInterval: 5 #(minutes)

  # The instance we want to skip the data collection
  # Each instance is separated by comma. Leave it empty if you don't want to skip any instance.
  # For exmaple: "instance1,instance2,instance3"
  instanceBlacklist: ""

  # The configurations for the agent.
  # One item in the list represents one agent task.
  # It supports the following types of agent tasks:
  # Metric:
  #   - powerFlex
  #   - powerScale
  #   - powerStore
  # Log:
  #   - powerFlexManager
  config:
      # The name of the agent task
    - name: device_powerflex_example
      # The type of the agent task (powerFlex | powerFlexManager | powerScale | powerStore)
      type: powerFlex
      # The connection url of the storage system (https://10.60.89.132)
      connectionUrl:
      # The instance type of the storage system (ProtectionDomain | StoragePool | Volume | Device)
      instanceType: Device
      # The username of the system
      username: 
      # The password of the system
      password: 
      # The metric API endpoint of the system
      metricEndpoint: /api/instances/{$instanceType}::{$id}/relationships/Statistics
      # The projectName created in InsightFinder application for this agent task
      IF_ProjectName: 
      # The systemName created in InsightFinder application for this agent task
      IF_SystemName: 
    
    - name: powerflex_Manager_example
      # The type of the agent task
      type: powerFlexManager
      # The connection url of the storage system
      connectionUrl: https://10.60.89.168
      # The username of the powerFlexManager system
      username: 
      # The password of the powerFlexManager system
      password: 
      # The projectName created in InsightFinder application for this agent task
      IF_ProjectName: 
      # The systemName created in InsightFinder application for this agent task
      IF_SystemName: 
    
    - name: powerscale_example
      # The type of the agent task
      type: powerScale
      # The connection url of the powerScale system
      connectionUrl: https://10.0.0.1:8080
      # The username of the powerScale system
      username: 
      # The password of the powerScale system
      password: 
      # The metric API endpoint of the powerScale system
      metricEndpoint: /platform/3/statistics/summary/client
      # The field name to set as the instanceName. (remote_addr, local_addr, local_name, remote_name) 
      # More field can be found at: https://developer.dell.com/apis/4088/versions/9.2.0.0/9.2.0.0_EMPIRE_OAS2.json/paths/~1platform~13~1statistics~1summary~1client/get
      instanceNameField: remote_addr
      # The field name to set as the timeStamp
      timeStampField: time

      # The first json class object key returned by the API.
      # For example, the power scale API returns {"client": {}}. The firstLayerkey should be "client".
      firstLayerkey: client

      # The projectName created in InsightFinder application for this agent task
      IF_ProjectName: 
      # The systemName created in InsightFinder application for this agent task
      IF_SystemName: 

    - name: powerStore_example
      # The type of the agent task
      type: powerStore
      # The connection url of the powerStore system
      connectionUrl: https://10.60.39.230
      # The username of the powerStore system
      username: 
      # The password of the powerStore system
      password: 
      # The metric API endpoint of the powerStore system
      metricEndpoint: /metrics/generate
      # The field name to set as the timestamp.
      timeStampField: timestamp

      # The metric entity need to collect from the powerStore API.
      # Available values can be found: https://developer.dell.com/apis/3898/versions/3.2.0/reference/openapi.json/paths/~1metrics~1generate/post
      metricType: performance_metrics_by_appliance

      # The metric data interval output from server. Choose from: Best_Available,Five_Sec,Twenty_Sec,Five_Mins,One_Hour,One_Day
      metric_interval_from_server: Five_Mins

      # (node, appliance)
      instanceType: appliance

      # The field from the reponse to set as the instanceName.
      instanceNameField: appliance_id

      # The projectName created in InsightFinder application for this agent task
      IF_ProjectName: 
      # The systemName created in InsightFinder application for this agent task
      IF_SystemName: 
