agent:
  server_port: 8080
  log_level: "INFO"

environment:
  send_to_all_environments: false
  
  environments:
    staging:
      - instancename: stg.insightfinder.com
        insightfinder:
          # InsightFinder Platform Configuration
          server_url: 
          username: 
          license_key: 
          
          # Metrics Project Configuration
          metrics_project_name: 
          metrics_system_name:
          metrics_project_type: Metric
          
          # Common Configuration
          cloud_type: OnPremise
          instance_type: OnPremise
          is_container: false
          sampling_interval: 60
        
        metriclistMap:
          ServiceNowTicketCreateDelay: "ServiceNow Ticket Creation"
          ServiceNowNoteRetrieve: "ServiceNow Feedback"

    production:
      - instancename: app.insightfinder.com
        insightfinder:
          # InsightFinder Platform Configuration
          server_url: 
          username: 
          license_key: 

          # Metrics Project Configuration
          metrics_project_name: 
          metrics_system_name: 
          metrics_project_type: Metric
          
          # Common Configuration
          cloud_type: OnPremise
          instance_type: OnPremise
          is_container: false
          sampling_interval: 60
        
        metriclistMap:
          ServiceNowTicketCreateDelay: "ServiceNow Ticket Creation"
          ServiceNowNoteRetrieve: "ServiceNow Feedback"

      - instancename: app2.insightfinder.com
        insightfinder:
          # InsightFinder Platform Configuration
          server_url: 
          username: 
          license_key: 

          # Metrics Project Configuration
          metrics_project_name: 
          metrics_system_name: 
          metrics_project_type: Metric
          
          # Common Configuration
          cloud_type: OnPremise
          instance_type: OnPremise
          is_container: false
          sampling_interval: 60
        
        metriclistMap:
          ServiceNowTicketCreateDelay: "ServiceNow Ticket Creation"
          ServiceNowNoteRetrieve: "ServiceNow Feedback"