# The image of the agent.
image: "docker.io/insightfinderinc/kubernetes-agent:0.0.4"

# The main configuration for prometheus to get metric data.
prometheus:
  
  # The API endpoint for the prometheus server.
  endpoint: "http://prometheus-server.monitor.svc.cluster.local"

  # Prometheus Basic Auth Creadentials. (Optional) 
  username: ""
  password: ""

# The main configuration for Loki to get log data.
loki:

  # The API endpoint for loki-gateway server.
  endpoint: "http://loki-gateway.monitor.svc.cluster.local"

  # Loki Basic Auth Creadentials. (Optional) 
  username: ""
  password: ""

# The configuration for InsightFinder
insightfinder:
  url: "https://app.insightfinder.com"  # The url of InsightFinder.
  user_name: ""                         # Username for InsightFinder.
  license_key: ""                       # license_key for that InsightFinder user.
  system_name: ""                       # The system created in InsightFinder website.

# Each project entry is a project that will be created in InsightFinder.
# Projects will get created automatically if they don't exist.
projects: []
  # - name: node-metrics
  #   type: metric
  #   target: node

  # - name: pod-metric
  #   type: metric
  #   target: pod
  #   namespace: namespace1

  # - name: pod-log
  #   type: log
  #   target: pod
  #   namespace: namespace2

  # - name: namespace-event
  #   type: event
  #   target: namespace
  #   namespace: namespace3

  # - name: pvc-metric
  #   type: metric
  #   target: pvc
  #   namespace: namespace3